# Copyright 2021 ecodeclub
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

services:
  mysql8:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "13306:3306"
  dbproxy-forward:
    image: flycash/dbproxy:dbproxy-v0.4
    volumes:
      - ../test/testdata/config/docker/dbproxy-forward.yaml:/app/dbproxy/config.yaml
      - ../test/testdata/config/docker/plugins/log.yaml:/app/dbproxy/plugins/log/config.yaml
      - ../test/testdata/config/docker/plugins/forward.yaml:/app/dbproxy/plugins/forward/config.yaml
    ports:
      - "8308:8308"
  dbproxy-sharding:
    image: flycash/dbproxy:dbproxy-v0.4
    volumes:
      - ../test/testdata/config/docker/dbproxy-sharding.yaml:/app/dbproxy/config.yaml
      - ../test/testdata/config/docker/plugins/log.yaml:/app/dbproxy/plugins/log/config.yaml
      - ../test/testdata/config/docker/plugins/sharding.yaml:/app/dbproxy/plugins/sharding/config.yaml
    ports:
      - "8309:8309"