// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go
//
// Generated by this command:
//
//	mockgen -source=./types.go -destination=mocks/logger.mock.go -package=logmocks -typed Logger
//
// Package logmocks is a generated GoMock package.
package logmocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Errorf mocks base method.
func (m *MockLogger) Errorf(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Errorf", varargs...)
}

// Errorf indicates an expected call of Errorf.
func (mr *MockLoggerMockRecorder) Errorf(format any, args ...any) *LoggerErrorfCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Errorf", reflect.TypeOf((*MockLogger)(nil).Errorf), varargs...)
	return &LoggerErrorfCall{Call: call}
}

// LoggerErrorfCall wrap *gomock.Call
type LoggerErrorfCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *LoggerErrorfCall) Return() *LoggerErrorfCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *LoggerErrorfCall) Do(f func(string, ...any)) *LoggerErrorfCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *LoggerErrorfCall) DoAndReturn(f func(string, ...any)) *LoggerErrorfCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Logf mocks base method.
func (m *MockLogger) Logf(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Logf", varargs...)
}

// Logf indicates an expected call of Logf.
func (mr *MockLoggerMockRecorder) Logf(format any, args ...any) *LoggerLogfCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logf", reflect.TypeOf((*MockLogger)(nil).Logf), varargs...)
	return &LoggerLogfCall{Call: call}
}

// LoggerLogfCall wrap *gomock.Call
type LoggerLogfCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *LoggerLogfCall) Return() *LoggerLogfCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *LoggerLogfCall) Do(f func(string, ...any)) *LoggerLogfCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *LoggerLogfCall) DoAndReturn(f func(string, ...any)) *LoggerLogfCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
