apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: dbproxy-mutate
webhooks:
  - name: z.dbproxy.webhook
    clientConfig:
      service:
        namespace: default
        name: dbproxy-webhook
        path: "/mutate"
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtakNDQW9LZ0F3SUJBZ0lVT2JEV1ZTcy9ZS3psOVVEQW8vU29ITndES1F3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEkwTURjd016RTBNelF3TUZvWERUSTVNRGN3TWpFME16UXdNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdVlGZlVoWnFlK3FJNVBKazRTdDAKVUphbEhldlNyYURDUU5ZOWUyRXR6aHUyMDZRYm9INDhPelM2WDhHK0ptWU53S1ZJc0pvY05NUCtXdjNpNnA2dwpqVkhNUS9EUzF0RGlScS9Vd0c4NXMxeStLSG85RzRGNHVxTjlZdEVlNk1ScUlrTWRER3B6Q3FkTlp4cDBPQXRRCi9xSHRUTXFMUjM3ZE1HUmJOMWxLcHp0RHB1MlM2MXdoWHo1RVV2Zm1qQjNpWmdPbHd3ZzYvN2htdUUrR25EbkIKVnd2UWJYM0hPNlZydi9qYWhMQy9FV0tITVpCTE9VaURqWGtLektVMWVBblFCVkRYWVZLeC9HclJCeW1rc0JacwpHcWpWZEQ5a1A3eUFxM29EL1RQUTBYT2czMGRsUjl3STFXVFY0TWZJQ1Z0dTh5MEFJMFJSNzI2NytUdUhRVjloCkF3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlYKSFE0RUZnUVUvaEZCNXBsdzU0akRTNnM5UXBnelVKVXFYemN3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUZnUgpsS1dvVUtmU3lYb2NGVFRmY1FjaytTZGdMNW14MzBZeC9zMjRkdUlyL1ZCQ2c1WEVUdDk4TmxQdGRLekxNMjFzClVsM2w4cDA0Z2k1aS9uai9HZGtGbC8rNDRoclVqODBHS2xLbVU2ektocEd5eUYxbm5zbENSRmVYbVJsRWs1SmwKbVF6YzU0WTczVmlNOVdndUhwRUxLS2ZmNTdzbmdQRHgvUE40QVJDZmdYYTJtZnNkc21telVaeng1T3BXR3dpawppZEFkMTRyaG0vOTlyWXR0UkJ2bnVieDJhVUxRWVplWE1aL3RtamVpT3B5bHVOc2ExK3RyYmtLcGdMajFOdlR6CmU1bHZ1aWlFemVZYTdPT2twRWs3d1hrOU85cEU3eTg1Z05WTkkvWWVSNFZpR3ZDV2lSOFlEWVAxTHF0TlFJRGYKZW1mWjJsM3R4SGRzc1RGaVFNQT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: [ "v1" ]
    sideEffects: None