apiVersion: v1
kind: Pod
metadata:
  name: test-pod1
spec:
  containers:
    - name: test-app
      image: flycash/dbproxy:testserver-v0.1
      ports:
        - containerPort: 8080
          hostPort: 8080