# permissions for end users to view dbproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dbproxy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: demo
    app.kubernetes.io/part-of: demo
    app.kubernetes.io/managed-by: kustomize
  name: dbproxy-viewer-role
rules:
- apiGroups:
  - proxy.meoying.com
  resources:
  - dbproxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - proxy.meoying.com
  resources:
  - dbproxies/status
  verbs:
  - get
